services:
  db_students_test:
    image: postgres
    container_name: db_students_test
    restart: always
    ports:
      - 5544:5432
    env_file:
      - .env.docker.test

  node_sorteador_app:
    container_name: node_sorteador_app
    build: ./back-end/
    ports:
      - 5000:5000
    depends_on:
      - db_students_test
    env_file:
      - .env.docker.test
