services:
  postgres_sorteador_db_test:
    image: postgres
    container_name: postgres_sorteador_db_test
    restart: always
    ports:
      - 5544:5432
    env_file:
      - .env.docker.test

  node_sorteador_app:
    container_name: node_sorteador_app
    build: ./back-end/
    ports:
      - 5000:5000
    depends_on:
      - postgres_sorteador_db_test
    env_file:
      - .env.docker.test
