services:
  postgres_sorteador_db:
    image: postgres
    container_name: postgres_sorteador_db
    restart: always
    ports:
      - 4457:5432
    env_file:
      - ./back-end/.env.docker
    volumes:
      - pg_sorteador_db:/var/lib/postgresql/data

  node_sorteador_app:
    container_name: node_sorteador_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - postgres_sorteador_db
    volumes:
      - ./back-end:/usr/src
    env_file:
      - ./back-end/.env.docker

  react_sorteador_app:
    container_name: react_sorteador_app
    build: ./front-end
    volumes:
      - build_react:/var/www/html
    env_file:
      - ./front-end/.env.docker

  nginx_sorteador_app:
    container_name: nginx_sorteador_app
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - postgres_sorteador_db
      - node_sorteador_app
      - react_sorteador_app

volumes:
  pg_sorteador_db:
  build_react:
